### ISSUE TITLE
规则替换URL为data URL数据后，data URL默认为text/plain文本形式，建议添加修改类型的功能

### ISSUE THREAD

**Issue by Gowee** [meowtec/Owl-redirector#13]

**Comment by meowtec** [comment]
有没有具体的需求场景？
感觉 mimetype 在这儿用途并不大，浏览器在处理 js css 时一般会忽略它。
Ajax 里面 js 好像又没法获取 type (跨域).

**Comment by Gowee** [comment]
比如在替换HTML时。
后来发现可以手动转换成data URL，选择第一个类型（URL）实现。
这个应用场景可能过于小众吧。
如果觉得没必要的话，请无视此issue。
