### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by BreathBlush** [meowtec/Owl-redirector#14]
有一个网站，启用了https，但里面的许多超链接都还是http的，导致诸多问题，经测试将http手动改为https即可。因此，我尝试将对该网站的所有http请求都redirect到https

我是这样写的

/^http:\/\/testurl.com$/

function (url){
  return url.replace('http:', 'https:')  
}

不知为何，无法实现跳转？

**Comment by meowtec** [comment]
extension.beforeRequest 对请求进行重定向处理的实现，是作为「中间人」向浏览器前端返回了一个 statusCode=307 的响应。对于浏览器前端来说，这个重定向就好像是服务器发起的一样。

而 https 网页加载 http 的内容，在请求发起前就被安全拦截掉了。所以扩展根本没有机会监听到请求，也就没办法进行重定向。

**Comment by BreathBlush** [comment]
感谢回复及说明，那这种情况能否通过脚本的形式探测网页中所有的http链接然后替换呢？

**Comment by meowtec** [comment]
可以。
http://open.chrome.360.cn/html/dev_content_scripts.html
照着这个写一个 manifest.json，一个 js 文件，就能在你的网页里面运行这个 js 脚本了。
然后用这个 js 从 dom 里面查找 http 资源，加载 https 的。

但是需要注意：
1. js 脚本运行于独立作用域，不能直接访问页面的 js 变量。
2. 如果加载多个 js，需要注意原来是阻塞加载的，现在变成非阻塞了。

**Comment by BreathBlush** [comment]
哈，明白了，感谢
