### ISSUE TITLE
匹配问题

### ISSUE THREAD

**Issue by chenxuuu** [meowtec/Owl-redirector#15]
为何用http_://www.baidu.com/_tn=__hao_pg_和_tn=__hao_pg*都无法匹配
https://www.baidu.com/s?tn=93489630_hao_pg&ie=utf-16&word=123

另外能给个屏蔽这种推广劫持的方案吗→_→ 

test时报错如下
![1111](https://cloud.githubusercontent.com/assets/10357394/15105177/0d22180a-15f2-11e6-9345-3d404edf2260.png)

**Comment by meowtec** [comment]
咦，报错了？有点奇怪啊。
你试试这个：

```
https://www.baidu.com/s?tn=*_hao_pg*
```

报错的问题我再看看
