### ISSUE TITLE
OSX 下不能用？

### ISSUE THREAD

**Issue by cyio** [meowtec/Owl-redirector#17]
如题

**Comment by meowtec** [comment]
我就是在 OSX 下开发的，怎么不能用？

**Comment by cyio** [comment]
osx 下背景页
![image](https://cloud.githubusercontent.com/assets/3146103/20001965/654b11cc-a2b9-11e6-8350-dc708b309367.png)

linux 下背景页
![image](https://cloud.githubusercontent.com/assets/3146103/20002030/ad3850ee-a2b9-11e6-863a-5ae1a0d30c04.png)

两个平台完全一样的配置，挺纳闷的

![image](https://cloud.githubusercontent.com/assets/3146103/20002111/1a2ef6bc-a2ba-11e6-9676-a4ce2dd8650e.png)

**Comment by meowtec** [comment]
osx 的 log 里面有 redirect 说明是重定向了啊

**Comment by cyio** [comment]
抱歉，被地址栏的表象蒙蔽了，只有 mac 下地址栏会显示出跳转地址，一直以为这个表现说明插件没起作用
刚找到可靠的测试方法，把翻墙代理关掉，尝试打开跳转地址就能看出区别
