### ISSUE TITLE
https不能重定向

### ISSUE THREAD

**Issue by SealinRepo** [meowtec/Owl-redirector#21]
https貌似不能重定向额,是协议限制不能劫持还是bug

**Comment by SealinRepo** [comment]
试了下,是URL栏的正则不能正常工作,在URL栏直接写完整地址可以转向,但是加进正则就不能匹配地址了

**Comment by meowtec** [comment]
发一下你的正则

**Comment by SealinRepo** [comment]
哈哈,原来是直接用*匹配的,我之前写的a-z0-9
