### ISSUE TITLE
谷歌商店中的扩展不见了，希望重新上架

### ISSUE THREAD

**Issue by BreathBlush** [meowtec/Owl-redirector#23]
如题，本地安装比较麻烦。而且不能同步，希望重新上架，很好用的扩展，谢谢！

**Comment by meowtec** [comment]
你不说我还不知道，几个月前被 Google 下架了，说描述不清楚，可能有误导信息什么的。
我编辑了一下，现在在审核。

**Comment by meowtec** [comment]
我看到已经重新上架了，你看一下

**Comment by BreathBlush** [comment]
已经看到，感谢
